<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PPTRevive.Application</RootNamespace>
    <AssemblyName>PPTRevive.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Roles\Rights\Commands\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Roles\Rights\Commands\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Roles\Rights\Commands\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Common\Interfaces\5x5prxdt.1uo~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="Aspose.Slides.NET" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
