// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeboqmgdranzlubelipd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlYm9xbWdkcmFuemx1YmVsaXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzUyOTcsImV4cCI6MjA1OTU1MTI5N30.Sq4UHcVgSjSy1trHYyZ5iIfxmsAlzF-BmXtS9tlmuMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);